version: "3.9"
services:
  database:
    image: postgres
    container_name: movie-database
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}

    networks:
      - movieNetwork
    volumes:
      - data:/var/lib/postgresql/data

  movieReminder:
    image: movie-reminder
    container_name: movie-reminder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MOVIE_PORT}:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
    networks:
      - movieNetwork

  cloudflare:
    image: cloudflare/cloudflared
    container_name: movie-reminder-cloudflare
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=$TUNNEL_TOKEN
    restart: unless-stopped
    networks:
      - movieNetwork

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    networks:
      - movieNetwork
networks:
  movieNetwork:

volumes:
  data:
