version: "3.9"
services:
  database:
    image: postgres
    container_name: movie-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: "Europe/Paris"
    networks:
      - movieNetwork
    volumes:
      - data:/var/lib/postgresql/data

  movieReminder:
    image: movie-reminder
    container_name: movie-reminder
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MOVIE_PORT}:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SHOW_SQL: ${SHOW_SQL}
      FORMAT_SHOW_SQL: ${FORMAT_SHOW_SQL}
      TZ: "Europe/Paris"
    restart: unless-stopped
    networks:
      - movieNetwork

networks:
  movieNetwork:

volumes:
  data:
