version: "3.8"
services:
  database:
    image: postgres
    container_name: movie-database
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      TZ: "Europe/Paris"
    networks:
      - movieNetwork
    volumes:
      - data:/var/lib/postgresql/data

  movieReminder:
    image: movie-reminder
    container_name: movie-reminder
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      SHOW_SQL: ${SHOW_SQL}
      FORMAT_SHOW_SQL: ${FORMAT_SHOW_SQL}
      TZ: "Europe/Paris"

    networks:
      - movieNetwork

  cloudflare:
    image: cloudflare/cloudflared
    container_name: movie-reminder-cloudflare
    command: tunnel run
    environment:
      TUNNEL_TOKEN: $TUNNEL_TOKEN
      TZ: "Europe/Paris"
    restart: unless-stopped
    networks:
      - movieNetwork

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8888:8080
    restart: unless-stopped
    environment:
      TZ: "Europe/Paris"
    networks:
      - movieNetwork
networks:
  movieNetwork:

volumes:
  data:
